name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  security-scan:
    needs: build
    uses: ./.github/workflows/docker-image-security-scan.yml
    secrets: inherit
