name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/docker.yml
    with:
      DOCKER_IMAGE_NAME: your-image-name
      DOCKER_IMAGE_TAG: latest
    secrets: inherit
