name: Docker Image Security Scan

on:
  workflow_call:
    secrets: inherit

jobs:
  scan:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 3000:3000
          - 27017:27017
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Compose services
      run: |
        cd path/to/your/docker-compose/directory  # Change this to the actual path if not in the root
        docker-compose build

    - name: Scan frontend image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ranizouaoui/frontend:latest

    - name: Scan backend image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ranizouaoui/backend:latest
